### ISSUE TITLE
Chat inputs are sent to everyone

### ISSUE THREAD

**Issue by skerit** [spigot-gillesm/RPGChest-Premium#14]
I'm having the same issue as #5, but I'm not using VentureChat (just plain old Essentials)

When I need to type in the name of an item or so, everyone sees what I'm typing.

Other plugins that use the chat to configure things (like Quest) don't have this problem.

**Comment by spigot-gillesm** [comment]
Okay, I'll find a way to fix this problem. Sorry for the inconvenience

**Comment by spigot-gillesm** [comment]
As I'm focusing on the per-player loot system, I'll try to fix this issue right after (along with other stuff)

**Comment by spigot-gillesm** [comment]
Hello again,

I installed EssentialsX along with all the EssentialsX plugins but when I type things (alone, in a test server with no chat configuration made) my inputs are not sent. Can you give me a bit more details? What configuration are you using? Is it well EssentialsXChat? There must be something you're doing that I'm not and it's probably related to the configurations (as I have none set up)

**Comment by spigot-gillesm** [comment]
As the ticket has been left unanswered for a long time I'm closing it. Feel free to re-open it if needed
