### ISSUE TITLE
Make chests lootable per person

### ISSUE THREAD

**Issue by skerit** [spigot-gillesm/RPGChest-Premium#15]
This is more of a feature request:
I want a chest that'll always be visible, but is lootable per player. So if 2 people are looking in the chest, they see different things. And once it's looted, they'll never see anything respawn in it.

Currently the chests disappear after it's been looted (so people can't do the same quest at the same time) and when it does reappear, they can loot it again.

**Comment by spigot-gillesm** [comment]
As this suggestion has been made a few times, I'll find the time to implement it. I know it's not the subject of this thread but if the despawning feature annoys you, you can de-activate it in the container/group configuration

**Comment by spigot-gillesm** [comment]
I've already started to code the feature and I'm close to a result. The first version of the per player loot system might not be "complete" but I'll work on it over time so all the other features are applicable to this kind of container

**Comment by spigot-gillesm** [comment]
I've pushed to per player loot system update! Right now, when using this system, the key feature is not working but I'll make it work with the per player loot system in a future update

I'm closing the ticket, feel free to open another if there's anything you want to say about this feature (or anything else)
