### ISSUE TITLE
Key Drop Bugs

### ISSUE THREAD

**Issue by Syrkulous** [spigot-gillesm/RPGChest-Premium#17]
Adding a mob drop to a key will create an internal error for the plugin causing it to stop working,
Reloading the plugin wont fix it, making the server need a restart to make it work.

When typing after attempting to choose a mob and chance for the drop, it'll constantly mark your messages as "Unknown mob type" or "Please type a chance to drop"

A mob can not be entered still (as it was thought to be fixed)

Edit : Ever since this happened, even after a restart, the plugin will start giving internal errors and wont work.

Currently using version 2.1.0.2

**Comment by Syrkulous** [comment]
Ever since this happened, even after a restart, the plugin will start giving internal errors and wont work.

**Comment by Syrkulous** [comment]
Currently using version 2.1.0.2

**Comment by spigot-gillesm** [comment]
Could you send me the error you get in the console (using pastebin) and the keys.yml file of your server?

I'll try to fix it as fast as I can. Sorry for the delay

**Comment by Syrkulous** [comment]
This shows whenever I do /rpgc m
https://pastebin.com/83Zshwsa

And this is the keys.yml that I have written down (I can't attach a file)
https://pastebin.com/R66z12jP

**Comment by spigot-gillesm** [comment]
Alright thanks, I'll look into it. As I've already started to rework the group system, it's going to take a little more time before the next update (with your issue fixed) is out. I'll do it asap

**Comment by spigot-gillesm** [comment]
Okay, I've found the key issue. As there are no ender dragon spawn egg (and the mob egg is used as a button in the key drops), the menu crashes. Unless this key drop is vital for your server, I recommend you to remove the ender dragon drop (manually) while I work on the update and this is fixed. Sorry for this issue

Edit: If you're not using the menu and do all manually, this issue doesn't affect the feature in itself, only the menu. So the ender dragon still drops the key

**Comment by spigot-gillesm** [comment]
It should be fixed now. If it is, please close the issue
