### ISSUE TITLE
I'm in trouble.

### ISSUE THREAD

**Issue by 849025143** [spigot-gillesm/RPGChest-Premium#20]
When I choose a box.
[10:50:40 INFO]: /!\[RPG Chest]/!\ Unable to set container coordinate: Null

**Comment by 849025143** [comment]
My version is 1.12.2
Server is Paper-1.12.2-b1618

**Comment by spigot-gillesm** [comment]
I just fixed the issue, I'll push the update now ;) It'll be up in 2 minutes. Sorry for the inconvenience

**Comment by 849025143** [comment]
It doesn't matter. Your serious attitude is very good.

**Comment by spigot-gillesm** [comment]
It should be fixed! Feel free to re-open the ticket if the problem persists

Thank you!
