### ISSUE TITLE
Problem with radius

### ISSUE THREAD

**Issue by kiloRs** [spigot-gillesm/RPGChest-Premium#27]
When attempting to change the radius of a container, the value doesn't change from the GUI menu.
Paper 1.15.2
Latest RPGC

**Comment by spigot-gillesm** [comment]
Hello

When left clicking the radius option, the value isn't increased at all? Is there any 'radius' option showing up in the container.yml file?

**Comment by spigot-gillesm** [comment]
As many changes have taken place since this issue has been opened I close the ticket. Feel free to open a new one if needed
