### ISSUE TITLE
suggest & bug

### ISSUE THREAD

**Issue by justicebearx** [spigot-gillesm/RPGChest-Premium#29]
First， Thank you for your support v1.12.2.   great！！
Now I can use it smoothly！
I found a problems：Particle effects are not displayed，I sure I turned it on.
Some prospectst：
Modify the configuration of the information ↓↓
![1](https://user-images.githubusercontent.com/68266386/99410768-cf1d4080-292d-11eb-8f6c-bbadad958f53.png)
Add en.lang xx.lang 

How about supporting mysql ??

**Comment by spigot-gillesm** [comment]
Hello and thank you,

I will double check the particle feature as I thought I fixed the problem
on 1.12.2, thanks for reporting the issue
Yes I will make the message formatable through a language file as soon as
I'm done with other important stuff (like the wiki)

I can add a MySQL support but only a very few users have asked for it. When
I'm done with previous suggestions (such as the language file) I'll work on
a MySQL compatibility

Le mar. 17 nov. 2020 à 16:46, justicebearx <notifications@github.com> a
écrit :

**Comment by justicebearx** [comment]
Thank you
