### ISSUE TITLE
problem key

### ISSUE THREAD

**Issue by ghost** [spigot-gillesm/RPGChest-Premium#4]
Is it normal that when I create a key with a rate of give on a skeleton it never gives me the key when I kill it?

**Comment by spigot-gillesm** [comment]
Hello!

No it's not normal, I'll check on my end to see if I have any problem regarding loot. Could you check one last time your configuration? (note that 100% = 1 in game and 25% = 0.25 in game)
As soon as I have tested it I'll come back to you

**Comment by spigot-gillesm** [comment]
Hello, as it has been quite a long time since you reported this issue can you tell me if you still have problems regarding loot rates?

**Comment by spigot-gillesm** [comment]
As the ticket is old now and no other issue has been reported, I'm closing the ticket. Feel free to open a new one if needed
