### ISSUE TITLE
Container name appear in the chat

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#5]
Hello Gilles !

I'm a new user of RPGChest and I start on 1.15.1
There is my issue : 
When I use the menu to create a Chest I write the name and it's print in the general chat

![Q8CDAU0](https://user-images.githubusercontent.com/37519498/72458197-6ffc1600-37c8-11ea-9427-fa0d5c3c3d77.png)

PS: We can see "The cooldown must ba a positive integer" but it's the default cooldown in config.yml so why this message ? (And it's not "ba" but "be")

Server PaperSpigot version 45 (MC 1.15.1)
RPGChest version 1.9.0.1

**Comment by spigot-gillesm** [comment]
Hello!

Are you using any chat management plugin?
The cooldown thing seems to happen with other people too but I couldn't replicate this issue I'll try to dig a bit more on this

(thanks for the details)

**Comment by Momonche** [comment]
Yes, I use VentureChat (Usefull for BungeeCord Inter-Server chat)

**Comment by spigot-gillesm** [comment]
Oh yes VentureChat, I had to fix a big incompatiblity with this plugin in the early versions of RPGChest but I couldn't prevent VentureChat to re-send message through its own code. I'm not sure I can prevent it from happening as it's a hard coded feature of VentureChat (which I don't own). I'll try again but one of my users told me he put himself in an isolated chat so no one could see his texts

**Comment by Momonche** [comment]
Ok, a lot of dev have problems with VentureChat integration :(

Keep me in touch if you can do something in the future !

**Comment by spigot-gillesm** [comment]
It doesn't surprise me as some VentureChat implementations are weird and there are not a lot of way to access VentureChat code
I close this issue as I can't really do anything about it right now but feel free to open a new one about this subject if there's another problem with VentureChat
