### ISSUE TITLE
Wiki or Plugin issue ?

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#6]
Hello Gilles !

I can read on the wiki in "Getting started" section : 

7. A menu named with the newly created container should appear with all the modifiable options in it

But there is no menu when is create the chest, so there is a wiki error or a plugin issue ?

Server PaperSpigot version 45 (MC 1.15.1)
RPGChest version 1.9.0.1

**Comment by spigot-gillesm** [comment]
Hello!

When you use the GUI by clicking on the paper icon to create a new chest, type in the name and click on the container, there should be a new chest icon with the given name in the containers menu. I just tried it to be sure there are no visible bug on my end but unfortunately I couldn't "replicate" your issue

Are there any errors in your server console?

**Comment by Momonche** [comment]
Ho yes, I don't understand the wiki like this, sorry for the issue
