### ISSUE TITLE
Can't create a new container after the 31th

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#7]
Hello Gilles !

I'm actually creating more than an hundred chest with your plugin but after the 31th, the paper icon disappear in the GUI : 

![t5iPjap](https://user-images.githubusercontent.com/37519498/72464394-75ac2880-37d5-11ea-9d99-eae2cfd56891.png)

Server PaperSpigot version 45 (MC 1.15.1)
RPGChest version 1.9.0.1

**Comment by spigot-gillesm** [comment]
Hello!

There is indeed icons appearing in the last line where there shouldn't be any. I'll fix it as soon as I can. I recommend you to use the file to create an additional chest while I fix it
Sorry for the inconvenience

**Comment by spigot-gillesm** [comment]
I fixed the issue and tested it and everything seems to work properly! Tell me if you still have bugs about this. Otherwise you can close this issue!

**Comment by Momonche** [comment]
Seems to work with RPGChest 1.9.0.2

Thanks Gilles !
